receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5555

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024        

exporters:
  prometheus:
    endpoint: 0.0.0.0:9090
    namespace: default
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  awss3:
    s3uploader:
        region: 'us-east-1'
        s3_bucket: 'otel-data-bhanu'
        s3_prefix: 'hello-app-telemetry-data'
        s3_partition: 'minute'
    
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [awss3,prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,awss3]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [awss3]
